server_config:
  credential_configurations:
    - credential_configuration_id: VehicleIdentificationCredential
      format: jwt_vc_json
      credential_definition:
        type:
          - VerifiableCredential
      display:
        - name: Vehicle Identification Credential
          locale: en
          logo:
            uri: https://smartparking.live/images/manufacturing_icon.png
            alt_text: OEM Logo

    - credential_configuration_id: VehicleRegistrationCredential
      format: jwt_vc_json
      credential_definition:
        type:
          - VerifiableCredential
      display:
        - name: Vehicle Registration Credential
          locale: en
          logo:
            uri: https://smartparking.live/images/transportation_authority.png
            alt_text: TA Logo

    - credential_configuration_id: VehicleOwnershipCredential
      format: jwt_vc_json
      credential_definition:
        type:
          - VerifiableCredential
      display:
        - name: Vehicle Ownership Credential
          locale: en
          logo:
            uri: https://smartparking.live/images/transportation_authority.png
            alt_text: TA Logo

    - credential_configuration_id: CollaborationCredential
      format: jwt_vc_json
      credential_definition:
        type:
          - VerifiableCredential
      display:
        - name: Collaboration Credential
          locale: en
          logo:
            uri: https://smartparking.live/images/service_provider_icon.png
            alt_text: PSP Logo
